#ifndef FORMSTATUS_H
#define FORMSTATUS_H


namespace UI {

enum FormStatus {LOGIN,MAIN,LOADFILE,VIEWASSETS,VIEWASSETTYPES,VIEWCUSTODIANS,EDITCUSTODIAN,EDITASSETTYPE,EDITASSET, NULLSTATUS};
}
#endif // FORMSTATUS_H
